// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Resto.Context;

#nullable disable

namespace Proyecto_Resto.Migrations
{
    [DbContext(typeof(RestoContext))]
    partial class RestoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proyecto_Resto.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.ItemReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("ItemProcesado")
                        .HasColumnType("bit");

                    b.Property<int>("idPlato")
                        .HasColumnType("int");

                    b.Property<int?>("idReserva")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idPlato");

                    b.HasIndex("idReserva");

                    b.ToTable("ItemReservas");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.Plato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricpion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Platos");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int?>("idCliente")
                        .HasColumnType("int");

                    b.Property<int?>("idRestaurante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idCliente");

                    b.HasIndex("idRestaurante");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.ItemReserva", b =>
                {
                    b.HasOne("Proyecto_Resto.Models.Plato", "Plato")
                        .WithMany()
                        .HasForeignKey("idPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Resto.Models.Reserva", "Reserva")
                        .WithMany("ItemReserva")
                        .HasForeignKey("idReserva");

                    b.Navigation("Plato");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.Reserva", b =>
                {
                    b.HasOne("Proyecto_Resto.Models.Cliente", "Cliente")
                        .WithMany("reservas")
                        .HasForeignKey("idCliente");

                    b.HasOne("Proyecto_Resto.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("idRestaurante");

                    b.Navigation("Cliente");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.Cliente", b =>
                {
                    b.Navigation("reservas");
                });

            modelBuilder.Entity("Proyecto_Resto.Models.Reserva", b =>
                {
                    b.Navigation("ItemReserva");
                });
#pragma warning restore 612, 618
        }
    }
}
